=== tommynguyen21032024/ossinsight/params.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "QuerySchema",
  "type": "object",
  "properties": {
    "cacheHours": {
      "description": "Cache time in hours, -1 indicates that the query cache will not expire.",
      "type": "number"
    },
    "refreshHours": {
      "description": "Refresh cache time in hours, -1 indicates not to refresh.",
      "type": "number"
    },
    "onlyFromCache": {
      "description": "Only return data from the cache.",
      "type": "boolean"
    },
    "params": {
      "description": "Query params declaration.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Params"
      }
    },
    "restrictions": {
      "description": "Special restrictions for params.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Restriction"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "cacheHours",
    "params"
  ],
  "definitions": {
    "Params": {
      "type": "object",
      "properties": {
        "name": {
          "description": "URL Search param name for the query.",
          "type": "string"
        },
        "type": {
          "description": "Define the parameter type.",
          "type": "string",
          "enum": ["array", "date-range"]
        },
        "column": {
          "description": "Define the parameter corresponding column name.",
          "type": "string"
        },
        "dateRangeTo": {
          "description": "Set in date-range should use that moment as `to` time.",
          "type": "string",
          "enum": ["now", "last-valid-datetime"],
          "default": "last-valid-datetime"
        },
        "replaces": {
          "description": "Define substring in the query sql template. Replacing uses `String.replaceAll`, please make sure the replacing substring is not substring of other texts.",
          "type": "string"
        },
        "template": {
          "description": "Replacing templates, mapped by search value",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "default": {
          "description": "Default input value.",
          "type": ["number", "string"]
        },
        "enums": {
          "description": "Enums for prefetching and validating, default is no prefetching and validating.",
          "oneOf": [
            {
              "description": "Predefined query params name.",
              "type": "string"
            },
            {
              "description": "The allowed values and should be prefetched.",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "pattern": {
          "description": "Regular expression for validating parameter value.",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "replaces"
      ]
    },
    "Restriction": {
      "type": "object",
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "enums": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "additionalProperties": false,
      "required": ["fields", "enums"]
    }
  }
}

=== tommynguyen21032024/ossinsight/api/queries/contributors-per-year/params.json
{
  "cacheHours": -1,
  "refreshHours": 240,
  "onlyFromCache": true,
  "params": [
    {
      "name": "repo",
      "replaces": "db_repos",
      "enums": "repo_subset"
    },
    {
      "name": "n",
      "replaces": "10",
      "enums": "n"
    },
    {
      "name": "year",
      "replaces": "2021"
    },
    {
      "name": "action",
      "replaces": "closed"
    },
    {
      "name": "merged",
      "replaces": "AND github_events.pr_merged IS TRUE",
      "template": {
        "true": "AND github_events.pr_merged IS TRUE",
        "*": ""
      }
    }
  ]
}
